disabled_rules:
  - statement_position

opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - trailing_closure

included: # paths to include during linting. `--path` is ignored if present.
  - ../Pod
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

force_cast: warning # Give warning only for force casting

force_try:
  severity: warning # Give warning only for force try

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    error: 3
  max_length:
    - 60
    - 80
  excluded:
    - id
    - to

type_name:
  min_length:
    error: 3
  max_length:
    - 60
    - 80
