platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'
use_frameworks!

def runtimepods
  pod 'AptoSDK'
  pod 'AptoUISDK'
  pod 'AptoObjCSDK'
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireNetworkActivityIndicator', '2.3.0'
  pod 'FTLinearActivityIndicator', '1.2.1'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SnapKit', '~> 5.0'
  pod 'Bond', '~> 7.6', :inhibit_warnings => true
  pod 'GoogleKit', '0.3.2', :inhibit_warnings => true
  pod 'PhoneNumberKit', '~> 3.2'
  pod 'TTTAttributedLabel', '2.0.0', :inhibit_warnings => true
  pod 'TrustKit', '~> 1.6'
  pod 'Down', '~> 0.8'
  pod 'PullToRefreshKit', '~> 0.8', :inhibit_warnings => true
  pod 'Mixpanel-swift', '~> 2.7', :inhibit_warnings => true
  pod 'TwilioVoice', '~> 3.0'
  pod 'Branch', '~> 0.33.1'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
end

target :Demo do
  runtimepods
  target 'UnitTests' do
    inherit! :search_paths
  end
  target 'SnapshotTests' do
    inherit! :search_paths
    pod 'SnapshotTesting', '~> 1.7.2'
  end
  target 'AutomationTests' do
    inherit! :search_paths
    pod 'KIF', '3.6.0', :configurations => ['Local','Stg','Dev']
    pod 'Alamofire-Synchronous', '4.0.0', :configurations => ['Local','Stg','Dev']
  end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited), PodsDummy_Pods=SomeOtherNamePodsDummy_Pods'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      if config.name == 'Local'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
      if config.name == 'Dev'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
      if config.name == 'Stg'
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
